//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корзина
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Корзина()
        {
            this.Купоны_и_скидки = new HashSet<Купоны_и_скидки>();
        }
    
        public int id_Корзины { get; set; }
        public Nullable<int> id_Пользователя { get; set; }
        public Nullable<int> id_Продукта { get; set; }
        public Nullable<int> id_Способа_доставки { get; set; }
        public Nullable<int> id_Способа_оплаты { get; set; }
        public string Сумма { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Продукт Продукт { get; set; }
        public virtual Способ_доставки Способ_доставки { get; set; }
        public virtual Способ_оплаты Способ_оплаты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Купоны_и_скидки> Купоны_и_скидки { get; set; }
    }
}
