//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукт()
        {
            this.Корзина = new HashSet<Корзина>();
        }
    
        public int id_Продукта { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<int> Цена { get; set; }
        public Nullable<int> id_Категории_товара { get; set; }
        public Nullable<int> id_Отзыва { get; set; }
    
        public virtual Категория_товара Категория_товара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Корзина> Корзина { get; set; }
        public virtual Отзывы Отзывы { get; set; }
    }
}
